language: python

python:
  - "2.6"
  - "2.7"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev
    - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install unittest2; fi
    - pip install cython numpy h5py

install: 
    - python setup.py build -f

script:  "python setup.py nosetests -s"
